[project]
name = "ws-subscriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.9.0",
    "pyserial>=3.5",
    "websockets>=15.0.1",
]
